### ISSUE TITLE
AdminConfiguration.Scopes config does not override defaults

### ISSUE THREAD

**Issue by Peperud** [skoruba/IdentityServer4.Admin#269] opened 2019-05-02 21:05 UTC
This could be a .NET Core DI/configuration issue, but it seems wrong nonetheless.

Configuration: 
```json
"AdminConfiguration": {
    "IdentityAdminBaseUrl": "http://localhost:9000",
    "IdentityAdminRedirectUri": "http://localhost:9000/signin-oidc",
    "IdentityServerBaseUrl": "http://localhost:5000",
    "ClientId": "adminui",
    "ClientSecret": "something",
    "OidcResponseType": "code id_token",
    "Scopes": [
      "openid",
      "profile",
      "email",
      "roles"
    ]
  }
```
AdminConfiguration,cs
```csharp
 public class AdminConfiguration : IAdminConfiguration
    {
        public string IdentityAdminBaseUrl { get; set; } = "http://localhost:9000";

        public string IdentityAdminRedirectUri { get; set; } = "http://localhost:9000/signin-oidc";

        public string IdentityServerBaseUrl { get; set; } = "http://localhost:5000";
        public string ClientId { get; set; } = AuthenticationConsts.OidcClientId;
        public string[] Scopes { get; set; } = AuthenticationConsts.Scopes.ToArray();
        public string ClientSecret { get; set; } = AuthenticationConsts.OidcClientSecret;
        public string OidcResponseType { get; set; } = AuthenticationConsts.OidcResponseType;
    }
```

AuthenticationConsts.cs
```csharp
 public class AuthenticationConsts
    {
        public const string IdentityAdminCookieName = "IdentityServerAdmin";
        public const string UserNameClaimType = "name";
        public const string SignInScheme = "Cookies";
        public const string OidcClientId = "adminui-wtf";
        public const string OidcClientSecret = "something-wtf";
        public const string OidcAuthenticationScheme = "oidc";
        public const string OidcResponseType = "code id_token wtf";
        public static List<string> Scopes = new List<string> { ScopeOpenId, ScopeProfile, ScopeEmail, ScopeRoles };

        public const string ScopeOpenId = "openid";
        public const string ScopeProfile = "profile";
        public const string ScopeEmail = "email";
        public const string ScopeRoles = "roles";

        public const string RoleClaim = "role";

        public const string AccountLoginPage = "Account/Login";
        public const string AccountAccessDeniedPage = "/Account/AccessDenied/";
    }
```

All AdminConfiguration properties get replaced with values from the config, except the scopes. They get **_added_**.  
![image](https://user-images.githubusercontent.com/12447865/57106681-e8768180-6ce2-11e9-8c43-86c24652dab4.png)

**Comment by skoruba** [comment] 2019-05-03 09:03
I'll check it - thanks!

**Comment by shepparddigital** [comment] 2019-05-03 14:05
I believe this is the intended behaviour of IdentityServer, see this video https://www.youtube.com/watch?v=J5p72gTdx_M&list=WL&index=5&t=0s at 1:00:58, when adding scopes they're added to the existing collection that's created by default by IdentityServer.

**Comment by Peperud** [comment] 2019-05-03 17:04
That shows intended behavior of C# (and I strongly agree with Scott & Brock that it is very much not intuitive). It shouldn't be the default behavior of IdentityServer IMO.

**Comment by shepparddigital** [comment] 2019-05-03 17:11
I entirely agree it's a strange way of doing things. There should at least be an option within IdentityServer to override the collection with your own, rather than it only providing the option to add.

I was just pointing out that the issue appears to be with IdentityServer itself and the way it managed the collection, rather than with this project.

**Comment by skoruba** [comment] 2019-06-16 11:39
I fixed this issue and I will release it in next beta version, thanks!

**Comment by skoruba** [comment] 2019-06-19 09:57
Fixed in new release.
Thanks

**Closed by skoruba** 2019-06-19 09:57 UTC
Labels: bug
