### ISSUE TITLE
Process is terminating due to StackOverflowException.

### ISSUE THREAD

**Issue by shepparddigital** [skoruba/IdentityServer4.Admin#271] opened 2019-05-03 16:57 UTC
Running IdentityServer4.Admin on a Mac (Core i7, 16MB Ram).

I have setup database connection strings and seeded the database. I have started the STS.Identity project, then started the Admin project. Visiting http://localhost:9000 I am able to login successfully and I am given the option to select from Manage Clients, Manage Users and other options, but when I select an option such as Manage Clients, the application exists and in the console I see the error 'Process is terminating due to StackOverflowException.'.

**Comment by skoruba** [comment] 2019-05-03 17:18
Can you provide whole exception? Thanks

**Comment by shepparddigital** [comment] 2019-05-03 17:29
Sadly, that's all the console shows. I've tried to debug the application and it doesn't show any more information either.

Coming from a Java background I'm not overly familiar with .Net Core, is there a setting or configuration that would allow me to change the log level?

**Comment by skoruba** [comment] 2019-05-13 21:43
Sorry for delay - you can change logging level in appsettings.json - did you reproduce this issue?
Thanks.

**Comment by skoruba** [comment] 2019-05-27 11:13
Any other details about this one?
Thanks.

**Comment by skoruba** [comment] 2019-06-16 11:35
I can't reproduce this issue, I am closing it now.
If you have any feedback on this, please let me know.
Thanks!

**Closed by skoruba** 2019-06-16 11:35 UTC
